// SPDX-License-Identifier: Apache-2.0
// Copyright 2026 Seamus Mullan and the Stratum contributors

/**
 * @file test_building_lod.cpp
 * @brief The per-building LOD chain: does it reduce, does it float, does it hole
 * @author Stratum Team
 * @version 0.1.0
 * @date 2026
 *
 * ================================================================================
 * WHY THESE TESTS CAN FAIL
 * ================================================================================
 *
 * A LOD chain is easy to test vacuously. "Every level has fewer triangles than the
 * last" passes for a chain that returns level 0 three times, because it does not;
 * "the bounding box is unchanged" passes for a chain that deletes every triangle
 * except the eight corners of the box. Both were written, and both were replaced.
 *
 * Every assertion here is one of six kinds, and each kind was chosen because a
 * specific plausible bug survives the other five:
 *
 *   - **A triangle multiset, not a triangle count.** Level 0 promises to carry
 *     every triangle of the input. The implementation that lost the roof -- 14 of
 *     400 triangles, the ones no SubMesh range claimed -- passed a count-based
 *     test of the ranges it did copy. It cannot pass a multiset comparison
 *     against the input.
 *
 *   - **An achieved ratio against a bound the broken behaviour misses by a
 *     mile.** The constrained simplifier stalls at 82% of level 0 on
 *     rule-generated geometry however low the ratio, so a test that accepted 85%
 *     would pass against exactly the behaviour build_building_lod() exists to
 *     beat. The bound is 0.2, and the "both mechanisms off" run is asserted to be
 *     strictly worse, so the number is a comparison this suite makes rather than
 *     a meshoptimizer constant it hard-codes.
 *
 *   - **Covered area, not triangle count, for the openings.** A window that
 *     half-collapses leaves a hole in a wall, and a hole costs triangles exactly
 *     as removing the window cleanly does. So the window tests measure the area
 *     of the opening that geometry still covers, and the suite includes the
 *     mutation that makes that number go to zero -- dropping the glazing instead
 *     of the reveal -- so the metric is known to be able to fail.
 *
 *   - **A RAY THROUGH EVERY OPENING, ON EVERY LEVEL OF A REAL CHAIN.** The kind
 *     that was missing, and the defect it was missing was a big one. The covered
 *     area above is a correct instrument and it was only ever pointed at
 *     drop_detail_keys() on a one-window fixture, so what build_building_lod()
 *     actually shipped went unmeasured -- and what it shipped had 24% of the
 *     front wall of the building see-through at its coarsest level, with all
 *     sixteen tests green over it. every_level_covers_the_openings_level_zero_
 *     covered walks every level of four configurations and counts rays. It is
 *     deliberately a DIFFERENT instrument from the one the implementation uses
 *     for the same job: the implementation shoots along each covering triangle's
 *     own normal, this walks a grid of world coordinates worked out by hand from
 *     the rule file. A test that re-ran the implementation's own measurement
 *     could only ever agree with it.
 *
 *   - **The ground plane, by position and not by bounding box.** A bounding box
 *     says nothing about whether the base ring is still the base ring. The tests
 *     compare the SET of quantised base positions across levels.
 *
 *   - **Two configurations that must disagree.** Every "the setting reached the
 *     geometry" test is a pair: with and without the ground band, with and
 *     without the detail drops, with and without the sloppy retry. A test that
 *     only ever runs the default configuration cannot tell a setting that works
 *     from a setting that is ignored.
 *
 * ### The two fixtures
 *
 * **The tower** is hand-built: a rectangular prism whose four walls are
 * subdivided 8 x 10 and a pyramid cap, welded, with real interior vertices and a
 * base ring of 32 distinct positions. It is what the ground-contact and
 * switch-distance questions are asked against, because its base ring is dense
 * enough for a simplifier to have somewhere to move it to.
 *
 * **The facade** is generated by the rule language itself -- extrude, gable roof,
 * `split` into floors and bays, `window()` in each bay -- because the quilt
 * problem this file exists for is a property of what the rule language emits and
 * a hand-built fixture would not have it. It is also the proof that E6 works on
 * E3's and E5's real output rather than on a mesh written to suit it. Its twelve
 * openings are at coordinates derived by hand from the rule text, which is what
 * makes the ray tests independent of the mesh they measure.
 *
 * ### What this suite still does not cover, stated rather than implied
 *
 * - The ONE-RING half of the lock dilation is inert on both fixtures. Removing it
 *   leaves every test here green. building_lod.cpp says so at dilate_lock_set()
 *   and gives its reasons for keeping it; this is the same fact from the suite's
 *   side.
 * - The corner samples in the implementation's own cover test are inert for the
 *   same reason: every failure either fixture produces opens a whole pane rather
 *   than half of one.
 *
 * Neither is a hole in a test. Both are code that no fixture here can distinguish
 * from its absence, recorded so that a green run is not read as covering them.
 *
 * Run just this suite with:
 * @code
 *     ./stratum_tests BuildingLod
 * @endcode
 */

#include "framework.hpp"

#include "procgen/building_lod.hpp"
#include "procgen/rules/interpreter.hpp"
#include "procgen/rules/op_facade.hpp"
#include "procgen/rules/parser.hpp"
#include "procgen/rules/registry.hpp"
#include "procgen/rules/shape.hpp"
#include "renderer/mesh.hpp"

#include <glm/glm.hpp>

#include <algorithm>
#include <array>
#include <cmath>
#include <cstddef>
#include <cstdint>
#include <map>
#include <set>
#include <string>
#include <vector>

namespace {

using stratum::MaterialId;
using stratum::MaterialKey;
using stratum::Mesh;
using stratum::SubMesh;
using stratum::Vertex;
using stratum::procgen::BuildingLod;
using stratum::procgen::BuildingLodConfig;
using stratum::procgen::build_building_lod;
using stratum::procgen::default_covering_plane_keys;
using stratum::procgen::default_facade_detail_drops;
using stratum::procgen::DetailDrop;
using stratum::procgen::drop_detail_keys;
using stratum::procgen::kBuildingLodSwitchFactor;
using stratum::procgen::rules::facade_material;
using stratum::procgen::rules::FacadePart;

// ============================================================================
// Mesh predicates
// ============================================================================

[[nodiscard]] std::size_t triangle_count(const Mesh& mesh) {
    return mesh.indices.size() / 3u;
}

/// Quantised position, so a vertex can be compared across a pass that renumbers
using PosKey = std::array<int64_t, 3>;

[[nodiscard]] PosKey pos_key(const glm::vec3& p) {
    const auto q = [](float v) { return static_cast<int64_t>(std::llround(v * 1.0e4f)); };
    return PosKey{q(p.x), q(p.y), q(p.z)};
}

/**
 * @brief A mesh reduced to a multiset of canonical position triples
 *
 * Content-addressed and material-blind, because this is the instrument for "is
 * this still the same geometry" and the material rule is a separate question with
 * its own tests. Every triangle of the index buffer is walked, whether or not a
 * SubMesh range claims it -- counting only the claimed ones is precisely the bug
 * this is the instrument for.
 *
 * The corner order is rotated to its smallest member rather than sorted, so a
 * triangle with the winding reversed does NOT compare equal to the original: a
 * level that flipped its normals is a different level.
 */
[[nodiscard]] std::multiset<std::array<PosKey, 3>> triangle_multiset(const Mesh& mesh) {
    std::multiset<std::array<PosKey, 3>> out;
    for (std::size_t t = 0; t + 2u < mesh.indices.size(); t += 3u) {
        if (mesh.indices[t] >= mesh.vertices.size() ||
            mesh.indices[t + 1u] >= mesh.vertices.size() ||
            mesh.indices[t + 2u] >= mesh.vertices.size()) {
            continue;
        }
        PosKey a = pos_key(mesh.vertices[mesh.indices[t]].position);
        PosKey b = pos_key(mesh.vertices[mesh.indices[t + 1u]].position);
        PosKey c = pos_key(mesh.vertices[mesh.indices[t + 2u]].position);
        // Rotate to the smallest corner, keeping the cycle.
        if (b < a && b < c) {
            std::swap(a, b);
            std::swap(b, c);
        } else if (c < a && c < b) {
            std::swap(b, c);
            std::swap(a, b);
        }
        out.insert(std::array<PosKey, 3>{a, b, c});
    }
    return out;
}

/// Triangles of @p mesh that some SubMesh range claims, which need not be all of them
[[nodiscard]] std::size_t claimed_triangles(const Mesh& mesh) {
    std::size_t claimed = 0;
    for (const SubMesh& sub : mesh.effective_submeshes()) {
        claimed += sub.index_count / 3u;
    }
    return claimed;
}

/// Every index addresses a vertex, and the index count is a whole number of triangles
[[nodiscard]] bool indices_are_sane(const Mesh& mesh) {
    if ((mesh.indices.size() % 3u) != 0u) {
        return false;
    }
    for (const uint32_t index : mesh.indices) {
        if (index >= mesh.vertices.size()) {
            return false;
        }
    }
    return true;
}

/// No NaN, no infinity, anywhere in the positions
[[nodiscard]] bool mesh_is_finite(const Mesh& mesh) {
    for (const Vertex& v : mesh.vertices) {
        if (!std::isfinite(v.position.x) || !std::isfinite(v.position.y) ||
            !std::isfinite(v.position.z)) {
            return false;
        }
    }
    return true;
}

/**
 * @brief The ranges tile the index buffer with no gap, no overlap and no repeat
 *
 * A gap is the failure that ate the roof, so it is checked here on every level
 * rather than only on the input.
 */
[[nodiscard]] bool submeshes_tile_exactly(const Mesh& mesh, std::string& reason) {
    const std::vector<SubMesh> ranges = mesh.effective_submeshes();
    std::set<uint32_t> keys;
    uint32_t cursor = 0;
    for (const SubMesh& sub : ranges) {
        if (sub.index_offset != cursor) {
            reason = "range at " + std::to_string(sub.index_offset) + " should start at " +
                     std::to_string(cursor);
            return false;
        }
        if ((sub.index_count % 3u) != 0u || sub.index_count == 0u) {
            reason = "range at " + std::to_string(sub.index_offset) + " holds " +
                     std::to_string(sub.index_count) + " indices";
            return false;
        }
        const MaterialKey key{sub.material, sub.variant};
        if (!keys.insert(key.packed()).second) {
            reason = "material " + std::string(stratum::material_id_name(sub.material)) +
                     " appears in two ranges";
            return false;
        }
        cursor += sub.index_count;
    }
    if (cursor != mesh.indices.size()) {
        reason = "ranges cover " + std::to_string(cursor) + " of " +
                 std::to_string(mesh.indices.size()) + " indices";
        return false;
    }
    return true;
}

/// The material keys a mesh carries, ascending
[[nodiscard]] std::vector<uint32_t> keys_of(const Mesh& mesh) {
    std::vector<uint32_t> keys;
    for (const SubMesh& sub : mesh.effective_submeshes()) {
        keys.push_back(MaterialKey{sub.material, sub.variant}.packed());
    }
    std::sort(keys.begin(), keys.end());
    keys.erase(std::unique(keys.begin(), keys.end()), keys.end());
    return keys;
}

/// Triangles carrying one material key
[[nodiscard]] std::size_t triangles_with_key(const Mesh& mesh, MaterialKey key) {
    std::size_t count = 0;
    for (const SubMesh& sub : mesh.effective_submeshes()) {
        if (sub.material == key.material && sub.variant == key.variant) {
            count += sub.index_count / 3u;
        }
    }
    return count;
}

/// Two meshes agree on every field a cache would hash
[[nodiscard]] bool meshes_are_identical(const Mesh& a, const Mesh& b) {
    if (a.vertices.size() != b.vertices.size()) return false;
    if (a.indices.size() != b.indices.size()) return false;
    if (a.submeshes.size() != b.submeshes.size()) return false;
    for (std::size_t i = 0; i < a.vertices.size(); ++i) {
        if (!(a.vertices[i] == b.vertices[i])) return false;
    }
    for (std::size_t i = 0; i < a.indices.size(); ++i) {
        if (a.indices[i] != b.indices[i]) return false;
    }
    for (std::size_t i = 0; i < a.submeshes.size(); ++i) {
        if (a.submeshes[i].index_offset != b.submeshes[i].index_offset) return false;
        if (a.submeshes[i].index_count != b.submeshes[i].index_count) return false;
        if (a.submeshes[i].material != b.submeshes[i].material) return false;
        if (a.submeshes[i].variant != b.submeshes[i].variant) return false;
    }
    return true;
}

// ============================================================================
// Ground-contact helpers
// ============================================================================

/// Lowest y any TRIANGLE of the mesh reaches, ignoring vertices nothing references
[[nodiscard]] double lowest_referenced_y(const Mesh& mesh) {
    double lowest = 1.0e30;
    for (const uint32_t index : mesh.indices) {
        if (index < mesh.vertices.size()) {
            lowest = std::min(lowest, static_cast<double>(mesh.vertices[index].position.y));
        }
    }
    return lowest;
}

/**
 * @brief Distinct referenced positions within @p band of @p floor
 *
 * Walks the INDEX buffer. A simplifier may leave a vertex in the buffer that no
 * triangle names any more, and counting those would report a base ring that never
 * shrinks however much of it was collapsed -- a test that cannot fail.
 */
[[nodiscard]] std::set<PosKey> base_positions(const Mesh& mesh, double floor, double band) {
    std::set<PosKey> out;
    for (const uint32_t index : mesh.indices) {
        if (index >= mesh.vertices.size()) {
            continue;
        }
        const glm::vec3& p = mesh.vertices[index].position;
        if (static_cast<double>(p.y) <= floor + band) {
            out.insert(pos_key(p));
        }
    }
    return out;
}

// ============================================================================
// The tower fixture
// ============================================================================

/**
 * @brief A prism with subdivided walls and a pyramid cap
 *
 * The walls are subdivided so that the mesh has interior vertices at all -- a
 * simplifier can do nothing with a box of twelve triangles, and a fixture it can
 * do nothing with answers no question about it. The base ring is @p cols * 4
 * distinct positions, which is what makes "did the ground move" a measurable
 * question rather than a four-corner coincidence.
 *
 * Walls are MaterialId::Wall and the cap is MaterialId::Roof, so the material
 * assertions have two keys to distinguish.
 */
[[nodiscard]] Mesh make_tower(int cols, int rows, float w, float d, float h, float cap) {
    Mesh mesh;
    std::vector<uint32_t> wall_indices;
    std::vector<uint32_t> roof_indices;

    const auto add = [&mesh](const glm::vec3& p, const glm::vec3& n) {
        Vertex v;
        v.position = p;
        v.normal = n;
        mesh.vertices.push_back(v);
        return static_cast<uint32_t>(mesh.vertices.size() - 1u);
    };

    struct Side {
        glm::vec3 origin;
        glm::vec3 along;
        glm::vec3 normal;
        float length;
    };
    const Side sides[4] = {
        {{0.0f, 0.0f, 0.0f}, {1.0f, 0.0f, 0.0f}, {0.0f, 0.0f, -1.0f}, w},
        {{w, 0.0f, 0.0f}, {0.0f, 0.0f, 1.0f}, {1.0f, 0.0f, 0.0f}, d},
        {{w, 0.0f, d}, {-1.0f, 0.0f, 0.0f}, {0.0f, 0.0f, 1.0f}, w},
        {{0.0f, 0.0f, d}, {0.0f, 0.0f, -1.0f}, {-1.0f, 0.0f, 0.0f}, d},
    };

    for (const Side& side : sides) {
        for (int r = 0; r < rows; ++r) {
            for (int c = 0; c < cols; ++c) {
                const float u0 = side.length * static_cast<float>(c) / static_cast<float>(cols);
                const float u1 = side.length * static_cast<float>(c + 1) / static_cast<float>(cols);
                const float y0 = h * static_cast<float>(r) / static_cast<float>(rows);
                const float y1 = h * static_cast<float>(r + 1) / static_cast<float>(rows);
                const uint32_t a = add(side.origin + side.along * u0 + glm::vec3(0, y0, 0), side.normal);
                const uint32_t b = add(side.origin + side.along * u1 + glm::vec3(0, y0, 0), side.normal);
                const uint32_t c2 = add(side.origin + side.along * u1 + glm::vec3(0, y1, 0), side.normal);
                const uint32_t d2 = add(side.origin + side.along * u0 + glm::vec3(0, y1, 0), side.normal);
                wall_indices.insert(wall_indices.end(), {a, b, c2, a, c2, d2});
            }
        }
    }

    const glm::vec3 apex(w * 0.5f, h + cap, d * 0.5f);
    const glm::vec3 corners[4] = {
        {0.0f, h, 0.0f}, {w, h, 0.0f}, {w, h, d}, {0.0f, h, d}};
    for (int i = 0; i < 4; ++i) {
        const glm::vec3 a = corners[i];
        const glm::vec3 b = corners[(i + 1) % 4];
        const glm::vec3 n = glm::normalize(glm::cross(b - a, apex - a));
        roof_indices.insert(roof_indices.end(), {add(a, n), add(b, n), add(apex, n)});
    }

    mesh.indices = wall_indices;
    mesh.indices.insert(mesh.indices.end(), roof_indices.begin(), roof_indices.end());
    mesh.submeshes.push_back(
        SubMesh{0u, static_cast<uint32_t>(wall_indices.size()), MaterialId::Wall, 0u});
    mesh.submeshes.push_back(SubMesh{static_cast<uint32_t>(wall_indices.size()),
                                     static_cast<uint32_t>(roof_indices.size()), MaterialId::Roof,
                                     0u});
    mesh.compute_bounds();
    return mesh;
}

// ============================================================================
// The rule fixtures
// ============================================================================

/**
 * @brief Run a rule file over a footprint and return what it generated
 *
 * The parse is asserted as a rendered string rather than as a boolean, so a
 * fixture whose rule text has a typo prints the parser's own caret diagnostic
 * instead of "0 != 400".
 */
[[nodiscard]] Mesh run_rule(const std::string& source, double width, double depth) {
    namespace rules = stratum::procgen::rules;
    const rules::ParseResult parsed = rules::parse(source, "building_lod_test.srl");
    CHECK_EQ(parsed.render_all(source), std::string{});
    const rules::GenerationResult result = rules::generate(
        parsed.file, rules::shape_from_rect(width, depth), {}, &rules::full_operations());
    CHECK_TRUE(result.ok());
    return result.build_mesh();
}

/**
 * @brief The E6 proof: a whole building from the rule language
 *
 * `extrude` raises the mass, `roof` puts a 35 degree gable on it, `select face`
 * picks the front, two `split`s cut it into floors and bays, and `window()`
 * glazes every middle bay. Three floors of four bays is twelve windows, and a
 * window is 28 triangles of which 26 are reveal, sill and frame.
 */
[[nodiscard]] std::string facade_source() {
    return "@start\n"
           "rule Main {\n"
           "    set(\"wall_thickness\", 0.4);\n"
           "    extrude(10.0);\n"
           "    roof(\"gable\", 35.0);\n"
           "    select face {\n"
           "        front : { Facade(); }\n"
           "        all   : { Shell(); }\n"
           "    }\n"
           "}\n"
           "rule Shell { }\n"
           "rule Facade {\n"
           "    split(y) {\n"
           "        4.0 : { Shopfront(); }\n"
           "        repeat { 2.0 : { UpperFloor(); } }\n"
           "    }\n"
           "}\n"
           "rule UpperFloor { split(x) { repeat { 1.5 : { Bay(); } } } }\n"
           "rule Bay {\n"
           "    split(x) {\n"
           "        0.4 : { Pier(); }\n"
           "        0.6 : { Window(); }\n"
           "        ~1.0 : { Pier(); }\n"
           "    }\n"
           "}\n"
           "rule Shopfront { wall_panel(); }\n"
           "rule Pier { wall_panel(); }\n"
           "rule Window { window(); }\n";
}

/// One glazed tile, 1.2 m by 2.0 m, in a 0.4 m wall
[[nodiscard]] Mesh one_window() {
    return run_rule("@start\nrule Main { set(\"wall_thickness\", 0.4); window(); }\n", 1.2, 2.0);
}

/// The opening one_window() glazes, in the plane the tile was built in
constexpr double kTileWidth = 1.2;
constexpr double kTileHeight = 2.0;

/**
 * @brief Area of the opening that geometry still covers, seen through the wall
 *
 * The tile lies in the xz plane and the wall's outward normal is -y, so the view
 * through the opening is the projection that drops y. A triangle counts when its
 * centroid projects strictly inside the opening, which excludes the sill -- it
 * hangs below the tile -- and gives the reveal an area of zero, because a jamb is
 * perpendicular to the wall and projects to a line.
 *
 * A fully covered opening therefore measures exactly kTileWidth * kTileHeight
 * whether or not the reveal and the sill are there, and an opening with the
 * glazing removed measures zero. That is the whole point: the number answers "can
 * you see through the wall", not "how much geometry is left".
 */
[[nodiscard]] double opening_coverage(const Mesh& mesh) {
    double total = 0.0;
    for (std::size_t t = 0; t + 2u < mesh.indices.size(); t += 3u) {
        const glm::vec3& a = mesh.vertices[mesh.indices[t]].position;
        const glm::vec3& b = mesh.vertices[mesh.indices[t + 1u]].position;
        const glm::vec3& c = mesh.vertices[mesh.indices[t + 2u]].position;
        const double cx = (static_cast<double>(a.x) + b.x + c.x) / 3.0;
        const double cz = (static_cast<double>(a.z) + b.z + c.z) / 3.0;
        constexpr double kInside = 1.0e-6;
        if (cx <= kInside || cx >= kTileWidth - kInside || cz <= kInside ||
            cz >= kTileHeight - kInside) {
            continue;
        }
        const double area = 0.5 * std::fabs(static_cast<double>(b.x - a.x) * (c.z - a.z) -
                                            static_cast<double>(c.x - a.x) * (b.z - a.z));
        total += area;
    }
    return total;
}

// ============================================================================
// Can you see through the wall
// ============================================================================

/**
 * @brief The twelve openings the facade fixture cuts, in world metres
 *
 * Derived by hand from the rule file, not read back out of the mesh, so a bug
 * that moves an opening cannot move the test with it. `split(x)` cuts the 6 m
 * front into four 1.5 m bays at 0, 1.5, 3.0 and 4.5; each Bay puts a 0.4 m pier,
 * then a 0.6 m window, so the pane centres are at 0.7, 2.2, 3.7 and 5.2.
 * `split(y)` cuts a 4 m shopfront then 2 m floors, so the floor centres are at
 * 5, 7 and 9.
 */
constexpr double kOpeningCentresX[4] = {0.70, 2.20, 3.70, 5.20};
constexpr double kOpeningCentresY[3] = {5.00, 7.00, 9.00};
constexpr double kOpeningWidth = 0.60;
constexpr double kOpeningHeight = 2.00;

/// The front wall's outer face. The glazing plane sits `reveal` metres behind it.
constexpr double kFrontWallZ = 3.00;

/**
 * @brief True when a +z ray at (@p x, @p y) meets some triangle at or beyond @p z_min
 *
 * The instrument for the question the whole file turns on: standing in front of
 * the building and looking at this point, is there anything there.
 *
 * DELIBERATELY INDEPENDENT of how build_building_lod() decides the same thing.
 * The implementation shoots one ray per covering triangle of level 0 along that
 * triangle's own normal; this walks a grid in world coordinates that were worked
 * out by hand from the rule file. A test that re-ran the implementation's own
 * measurement could only ever agree with it.
 *
 * The @p z_min floor excludes the BACK wall of the building, which a ray through
 * a hole in the front wall would otherwise hit -- and hitting the back wall
 * through a hole is exactly the failure being looked for, not the absence of one.
 */
[[nodiscard]] bool front_wall_is_solid_at(const Mesh& mesh, double x, double y, double z_min) {
    for (std::size_t t = 0; t + 2u < mesh.indices.size(); t += 3u) {
        if (mesh.indices[t] >= mesh.vertices.size() ||
            mesh.indices[t + 1u] >= mesh.vertices.size() ||
            mesh.indices[t + 2u] >= mesh.vertices.size()) {
            continue;
        }
        const glm::vec3& a = mesh.vertices[mesh.indices[t]].position;
        const glm::vec3& b = mesh.vertices[mesh.indices[t + 1u]].position;
        const glm::vec3& c = mesh.vertices[mesh.indices[t + 2u]].position;

        // Barycentric coordinates of (x, y) in the triangle's xy projection. A
        // triangle edge-on to the wall has a zero determinant and covers nothing.
        const double det = static_cast<double>(b.y - c.y) * (a.x - c.x) +
                           static_cast<double>(c.x - b.x) * (a.y - c.y);
        if (std::fabs(det) < 1.0e-12) {
            continue;
        }
        const double l1 = (static_cast<double>(b.y - c.y) * (x - c.x) +
                           static_cast<double>(c.x - b.x) * (y - c.y)) /
                          det;
        const double l2 = (static_cast<double>(c.y - a.y) * (x - c.x) +
                           static_cast<double>(a.x - c.x) * (y - c.y)) /
                          det;
        const double l3 = 1.0 - l1 - l2;
        if (l1 < -1.0e-9 || l2 < -1.0e-9 || l3 < -1.0e-9) {
            continue;
        }
        if (l1 * a.z + l2 * b.z + l3 * c.z >= z_min) {
            return true;
        }
    }
    return false;
}

/// Sample points per opening, per axis. 25 rays per opening, 300 for the facade.
constexpr int kOpeningSamples = 5;

/**
 * @brief How many of the twelve openings' sample points you can see through
 *
 * Counted rather than measured as an area because a count needs no projection
 * basis and no winding, and because the answer that matters is binary per point.
 *
 * @param mesh Any level of a chain built from facade_source() at 6 x 4 m
 * @return Open sample points, out of 12 * kOpeningSamples^2
 */
[[nodiscard]] int open_sample_points(const Mesh& mesh) {
    int open = 0;
    for (const double cx : kOpeningCentresX) {
        for (const double cy : kOpeningCentresY) {
            for (int r = 0; r < kOpeningSamples; ++r) {
                for (int c = 0; c < kOpeningSamples; ++c) {
                    const double x = cx - kOpeningWidth * 0.5 +
                                     kOpeningWidth * (c + 0.5) / kOpeningSamples;
                    const double y = cy - kOpeningHeight * 0.5 +
                                     kOpeningHeight * (r + 0.5) / kOpeningSamples;
                    if (!front_wall_is_solid_at(mesh, x, y, kFrontWallZ)) {
                        ++open;
                    }
                }
            }
        }
    }
    return open;
}

/// Every sample point of every opening
constexpr int kOpeningSampleTotal = 12 * kOpeningSamples * kOpeningSamples;

/// Distinct referenced positions at or below @p ceiling metres
[[nodiscard]] std::set<PosKey> positions_below(const Mesh& mesh, double ceiling) {
    std::set<PosKey> out;
    for (const uint32_t index : mesh.indices) {
        if (index < mesh.vertices.size() &&
            static_cast<double>(mesh.vertices[index].position.y) <= ceiling) {
            out.insert(pos_key(mesh.vertices[index].position));
        }
    }
    return out;
}

/**
 * @brief Area of the convex hull of the referenced positions in plan
 *
 * The footprint a player sees from above, and the thing a clusterer pulls a
 * corner in on. A bounding box cannot see a corner cut off at 45 degrees; a hull
 * can.
 */
[[nodiscard]] double plan_hull_area(const Mesh& mesh) {
    std::vector<std::array<double, 2>> points;
    for (const uint32_t index : mesh.indices) {
        if (index < mesh.vertices.size()) {
            points.push_back({static_cast<double>(mesh.vertices[index].position.x),
                              static_cast<double>(mesh.vertices[index].position.z)});
        }
    }
    std::sort(points.begin(), points.end());
    points.erase(std::unique(points.begin(), points.end()), points.end());
    if (points.size() < 3u) {
        return 0.0;
    }
    const auto cross = [](const std::array<double, 2>& o, const std::array<double, 2>& a,
                          const std::array<double, 2>& b) {
        return (a[0] - o[0]) * (b[1] - o[1]) - (a[1] - o[1]) * (b[0] - o[0]);
    };
    std::vector<std::array<double, 2>> hull(points.size() * 2u);
    std::size_t k = 0;
    for (std::size_t i = 0; i < points.size(); ++i) {
        while (k >= 2u && cross(hull[k - 2u], hull[k - 1u], points[i]) <= 0.0) --k;
        hull[k++] = points[i];
    }
    for (std::size_t i = points.size() - 1u, floor = k + 1u; i > 0; --i) {
        while (k >= floor && cross(hull[k - 2u], hull[k - 1u], points[i - 1u]) <= 0.0) --k;
        hull[k++] = points[i - 1u];
    }
    hull.resize(k - 1u);
    double twice = 0.0;
    for (std::size_t i = 0; i < hull.size(); ++i) {
        const std::array<double, 2>& u = hull[i];
        const std::array<double, 2>& v = hull[(i + 1u) % hull.size()];
        twice += u[0] * v[1] - v[0] * u[1];
    }
    return std::fabs(twice) * 0.5;
}

/// The keys the default table drops at the first simplified level
[[nodiscard]] std::vector<MaterialKey> first_drops() {
    std::vector<MaterialKey> keys;
    for (const DetailDrop& drop : default_facade_detail_drops()) {
        if (drop.from_ratio == 0u) {
            keys.push_back(drop.key);
        }
    }
    return keys;
}

} // namespace

// ============================================================================
// Level 0: what it must not lose
// ============================================================================

/**
 * Level 0 carries every triangle of the input, including the ones no SubMesh
 * range claims.
 *
 * This is the roof test. GenerationResult::build_mesh() opens no range for a
 * terminal whose faces are all MaterialId::Default, so those triangles sit in a
 * GAP between two ranges -- 14 of the facade fixture's 400, which are the roof and
 * the three unglazed walls. An implementation that walks effective_submeshes()
 * and copies what it finds deletes the roof off the building and reports nothing.
 *
 * Asserted as a multiset of content-addressed triangles, so reordering the index
 * buffer, renumbering the vertices and coalescing the ranges are all allowed and
 * losing one triangle is not.
 */
TEST(BuildingLod, level_zero_keeps_every_triangle_including_the_ones_no_range_claims) {
    const Mesh building = run_rule(facade_source(), 6.0, 4.0);
    CHECK_TRUE(triangle_count(building) > 300);

    // The fixture really does have the gap this test is about; without it the
    // test would pass for the wrong reason.
    const std::size_t claimed = claimed_triangles(building);
    CHECK_TRUE(claimed < triangle_count(building));

    const BuildingLod lod = build_building_lod(building);
    if (lod.levels.empty()) {
        stratum::test::report_failure(__FILE__, __LINE__, "the chain has a level 0",
                                      "build_building_lod returned nothing");
        return;
    }

    const Mesh& level0 = lod.levels[0];
    CHECK_EQ(triangle_count(level0), triangle_count(building));

    // Level 0 is NEVER WELDED, and a triangle multiset cannot say so -- a weld
    // moves no triangle and loses none, it only merges the vertices behind them.
    // The vertex count is the one number that can tell them apart: the relaxed
    // weld this file builds its simplification base with takes this fixture from
    // 802 vertices to 592, and shipping that as level 0 would close every UV seam
    // on the mesh the player stands in front of.
    CHECK_EQ(level0.vertices.size(), building.vertices.size());

    // Same multiset of triangles, same windings. Reordering, renumbering and
    // range coalescing are all allowed; losing one triangle is not.
    const std::multiset<std::array<PosKey, 3>> before = triangle_multiset(building);
    const std::multiset<std::array<PosKey, 3>> after = triangle_multiset(level0);
    CHECK_EQ(after.size(), triangle_count(building));
    CHECK_TRUE(before == after);

    // The unclaimed triangles arrive under the Default slot, which is what
    // Mesh::sort_submeshes_by_material() promises for the same case, and level 0
    // claims all of its own.
    CHECK_EQ(claimed_triangles(level0), triangle_count(level0));
    CHECK_EQ(triangles_with_key(level0, MaterialKey{MaterialId::Default, 0u}),
             triangle_count(building) - claimed);
}

/// Level 0 states each material once, ascending, with the ranges tiling exactly
TEST(BuildingLod, level_zero_coalesces_the_ranges_to_one_per_material) {
    const Mesh building = run_rule(facade_source(), 6.0, 4.0);

    // The rule mesh appends one range per terminal, so there are far more ranges
    // than materials before the chain touches it.
    CHECK_TRUE(building.submeshes.size() > 20);

    const BuildingLod lod = build_building_lod(building);
    if (lod.levels.empty()) {
        stratum::test::report_failure(__FILE__, __LINE__, "the chain has a level 0",
                                      "build_building_lod returned nothing");
        return;
    }

    const Mesh& level0 = lod.levels[0];
    std::string reason;
    if (!submeshes_tile_exactly(level0, reason)) {
        stratum::test::report_failure(__FILE__, __LINE__, "level 0 submeshes tile", reason);
    }

    // One range per distinct key the input carried, plus the Default slot the
    // unclaimed triangles land in.
    const bool has_gap = claimed_triangles(building) < triangle_count(building);
    std::vector<uint32_t> expected = keys_of(building);
    if (has_gap) {
        expected.push_back(MaterialKey{MaterialId::Default, 0u}.packed());
        std::sort(expected.begin(), expected.end());
        expected.erase(std::unique(expected.begin(), expected.end()), expected.end());
    }
    CHECK_EQ(level0.submeshes.size(), expected.size());

    // Ascending by packed key, which is what makes the layout a function of the
    // input rather than of the order the terminals happened to be appended in.
    for (std::size_t i = 1; i < level0.submeshes.size(); ++i) {
        const MaterialKey previous{level0.submeshes[i - 1u].material,
                                   level0.submeshes[i - 1u].variant};
        const MaterialKey current{level0.submeshes[i].material, level0.submeshes[i].variant};
        CHECK((previous.packed()) < (current.packed()));
    }
}

// ============================================================================
// Degenerate input
// ============================================================================

/// Nothing usable is not an error and is not a crash
TEST(BuildingLod, an_unusable_mesh_produces_no_levels) {
    const BuildingLod empty = build_building_lod(Mesh{});
    CHECK_TRUE(empty.levels.empty());
    CHECK_TRUE(empty.switch_distances.empty());
    CHECK_FALSE(empty.is_valid());

    // A mesh whose indices do not address its own vertices is refused rather than
    // handed to meshoptimizer, which reads out of bounds on one.
    Mesh malformed;
    malformed.vertices.resize(3);
    malformed.indices = {0u, 1u, 7u};
    const BuildingLod refused = build_building_lod(malformed);
    CHECK_TRUE(refused.levels.empty());

    // Vertices but no triangle.
    Mesh no_triangles;
    no_triangles.vertices.resize(4);
    const BuildingLod nothing = build_building_lod(no_triangles);
    CHECK_TRUE(nothing.levels.empty());
}

/**
 * drop_detail_keys() refuses the same malformed mesh build_building_lod() does.
 *
 * It is a PUBLIC entry point -- the header offers it to a caller building a
 * billboard without the rest of the chain -- and it walks the vertex array by
 * index while computing the result's bounds. Before this refusal existed it
 * checked only that there were three indices and some vertices, so a mesh whose
 * indices do not address its own vertices was an out-of-bounds READ: with a
 * hardened libstdc++ the same call aborts on `__n < this->size()` instead, which
 * is how it was found.
 *
 * Asserted for both an index past the end and an index into an empty array,
 * because the two take different routes through the function.
 */
TEST(BuildingLod, drop_detail_keys_refuses_a_mesh_whose_indices_are_out_of_range) {
    Mesh malformed;
    malformed.vertices.resize(3);
    malformed.vertices[0].position = {0.0f, 0.0f, 0.0f};
    malformed.vertices[1].position = {1.0f, 0.0f, 0.0f};
    malformed.vertices[2].position = {0.0f, 1.0f, 0.0f};
    malformed.indices = {0u, 1u, 9999u};

    const Mesh dropped = drop_detail_keys(malformed, {});
    CHECK_TRUE(dropped.indices.empty());
    CHECK_TRUE(dropped.vertices.empty());

    // And one whose indices are in range still works, so the refusal above is
    // the malformed case and not this function refusing everything.
    Mesh sound = malformed;
    sound.indices = {0u, 1u, 2u};
    const Mesh kept = drop_detail_keys(sound, {});
    CHECK_EQ(triangle_count(kept), std::size_t{1});
    CHECK_TRUE(indices_are_sane(kept));
}

/**
 * A building of one triangle gets a chain of exactly one level.
 *
 * Every ratio is asked for and every ratio fails: a target below three indices is
 * floored at three, which is the whole input, so no level can beat the previous
 * one by kMinLevelReduction and each is dropped ALONG WITH ITS SWITCH DISTANCE.
 * The two arrays staying the same length is the assertion -- a chain whose
 * distances outnumber its levels indexes out of bounds in the renderer.
 */
TEST(BuildingLod, a_single_triangle_building_has_only_level_zero) {
    Mesh triangle;
    triangle.vertices.resize(3);
    triangle.vertices[0].position = {0.0f, 0.0f, 0.0f};
    triangle.vertices[1].position = {4.0f, 0.0f, 0.0f};
    triangle.vertices[2].position = {0.0f, 6.0f, 0.0f};
    triangle.indices = {0u, 1u, 2u};
    triangle.compute_bounds();

    const BuildingLod lod = build_building_lod(triangle);
    CHECK_EQ(lod.levels.size(), std::size_t{1});
    CHECK_EQ(lod.switch_distances.size(), std::size_t{1});
    CHECK_TRUE(lod.is_valid());
    CHECK_EQ(triangle_count(lod.levels[0]), std::size_t{1});
    CHECK_NEAR(static_cast<double>(lod.switch_distances[0]), 0.0, 1e-9);

    // level_for_distance() must stay in range for a one-level chain at any
    // distance, which is what a renderer asks it.
    CHECK_EQ(lod.level_for_distance(0.0f), std::size_t{0});
    CHECK_EQ(lod.level_for_distance(10000.0f), std::size_t{0});
}

// ============================================================================
// The ground contact
// ============================================================================

/**
 * Every position of the base ring survives at every level, and the ground band is
 * what makes that true.
 *
 * A building whose base moves floats above the terrain or sinks into it, and that
 * reads from much further away than the detail the level traded for it.
 *
 * The second half is the part that stops the first from being vacuous. With
 * `ground_band` at zero the same call loses base positions outright -- measured
 * on this fixture the coarsest level's lowest vertex rises from y = 0 to y = 2 m,
 * taking the whole building off the ground. If that ever stops being true, this
 * test fails and the lock has stopped being load-bearing; that is a fact worth
 * finding out about rather than a bound to relax.
 */
TEST(BuildingLod, the_base_ring_survives_every_level) {
    const Mesh tower = make_tower(8, 10, 12.0f, 8.0f, 20.0f, 5.0f);

    BuildingLodConfig cfg;
    cfg.detail_drops.clear(); // no facade materials here; keep the question to the lock
    const BuildingLod locked = build_building_lod(tower, cfg);
    if (locked.levels.size() < 2u) {
        stratum::test::report_failure(__FILE__, __LINE__, "the tower produced a simplified level",
                                      "chain has " + std::to_string(locked.levels.size()) +
                                          " level(s)");
        return;
    }

    const double floor = lowest_referenced_y(locked.levels[0]);
    const std::set<PosKey> ring = base_positions(locked.levels[0], floor, 0.05);
    CHECK_TRUE(ring.size() >= 32u);

    for (std::size_t i = 1; i < locked.levels.size(); ++i) {
        const std::set<PosKey> kept = base_positions(locked.levels[i], floor, 0.05);
        if (kept.size() != ring.size()) {
            stratum::test::report_failure(
                __FILE__, __LINE__, "every base position survives",
                "level " + std::to_string(i) + " keeps " + std::to_string(kept.size()) + " of " +
                    std::to_string(ring.size()) + " base positions");
        }
        for (const PosKey& position : ring) {
            CHECK_TRUE(kept.find(position) != kept.end());
        }
        CHECK_NEAR(lowest_referenced_y(locked.levels[i]), floor, 1e-6);
    }

    // The same chain with the lock switched off does NOT keep the ground.
    BuildingLodConfig loose = cfg;
    loose.ground_band = 0.0f;
    const BuildingLod unlocked = build_building_lod(tower, loose);
    if (unlocked.levels.size() < 2u) {
        stratum::test::report_failure(
            __FILE__, __LINE__, "the unlocked chain has a simplified level to compare",
            "with ground_band = 0 the chain has " + std::to_string(unlocked.levels.size()) +
                " level(s), so the locked run above proves nothing");
        return;
    }

    const std::set<PosKey> coarse =
        base_positions(unlocked.levels.back(), floor, 0.05);
    if (!(coarse.size() < ring.size())) {
        stratum::test::report_failure(
            __FILE__, __LINE__, "the ground band is what keeps the base ring",
            "with ground_band = 0 the coarsest level still keeps " +
                std::to_string(coarse.size()) + " of " + std::to_string(ring.size()) +
                " base positions, so the locked run above proves nothing");
    }
}

// ============================================================================
// The quilt: does the chain actually reduce
// ============================================================================

/**
 * A rule-generated facade reaches a third of its triangles, watertight.
 *
 * THE point of the file. A rule facade is a quilt of small open shells whose
 * boundaries do not line up, and meshopt_simplify returns 82% of level 0 on it at
 * a requested 0.5, 0.25 and 0.1 alike. The bound here is 0.35, which that
 * behaviour misses by a mile.
 *
 * A THIRD, not the tenth an earlier version of this file claimed. That tenth was
 * reached by dropping the window frames and letting the simplifier take the
 * glazing, which left 24% of the front wall see-through -- see
 * every_level_covers_the_openings_level_zero_covered, which is the test that says
 * so. The covering plane costs what it costs: twelve window frames are 96
 * triangles that cannot go while the openings are still cut.
 *
 * The number is not hard-coded against meshoptimizer: the second half runs the
 * same input with both of this file's mechanisms disabled and requires the
 * default to be strictly better. If a future meshoptimizer simplifies a quilt on
 * its own, that comparison is what says so.
 */
TEST(BuildingLod, a_rule_generated_facade_reaches_its_ratios) {
    const Mesh building = run_rule(facade_source(), 6.0, 4.0);
    const BuildingLod lod = build_building_lod(building);

    if (lod.levels.size() < 2u) {
        stratum::test::report_failure(__FILE__, __LINE__, "the facade chain has coarse levels",
                                      "chain has " + std::to_string(lod.levels.size()) +
                                          " level(s)");
        return;
    }

    const std::size_t level0 = triangle_count(lod.levels[0]);
    CHECK_TRUE(level0 > 0);

    const double coarsest =
        static_cast<double>(triangle_count(lod.levels.back())) / static_cast<double>(level0);
    if (!(coarsest <= 0.35)) {
        stratum::test::report_failure(
            __FILE__, __LINE__, "the coarsest level is at most a third of level 0",
            std::to_string(triangle_count(lod.levels.back())) + " of " + std::to_string(level0) +
                " triangles is " + std::to_string(coarsest) +
                ", which is the stall this file exists to beat");
    }

    // Monotone, non-empty, finite and well-formed at every level.
    for (std::size_t i = 1; i < lod.levels.size(); ++i) {
        CHECK_TRUE(triangle_count(lod.levels[i]) < triangle_count(lod.levels[i - 1u]));
        CHECK_TRUE(triangle_count(lod.levels[i]) > 0);
        CHECK_TRUE(mesh_is_finite(lod.levels[i]));
        CHECK_TRUE(indices_are_sane(lod.levels[i]));
        std::string reason;
        if (!submeshes_tile_exactly(lod.levels[i], reason)) {
            stratum::test::report_failure(__FILE__, __LINE__, "every level's submeshes tile",
                                          "level " + std::to_string(i) + ": " + reason);
        }
    }

    // With the detail drop and the sloppy retry both off, the same geometry goes
    // nowhere. This is the comparison that makes the bound above meaningful.
    BuildingLodConfig bare;
    bare.detail_drops.clear();
    bare.allow_sloppy = false;
    const BuildingLod stalled = build_building_lod(building, bare);

    // levels.back() IS level 0 when the bare chain has only level 0, which makes
    // stalled_ratio 1.0 and both comparisons below unconditionally true. That is
    // not a pass, it is the test going quiet: the relaxed weld failing outright
    // collapses this chain to one level, and that is one of the regressions this
    // test is here to catch rather than to skip.
    if (stalled.levels.size() < 2u) {
        stratum::test::report_failure(
            __FILE__, __LINE__, "the bare chain has a simplified level to compare",
            "the bare chain has " + std::to_string(stalled.levels.size()) +
                " level(s), so it cannot be compared and the bound above proves nothing");
        return;
    }
    const double stalled_ratio =
        static_cast<double>(triangle_count(stalled.levels.back())) / static_cast<double>(level0);
    if (!(coarsest < stalled_ratio)) {
        stratum::test::report_failure(
            __FILE__, __LINE__, "the drop and the sloppy retry are doing the work",
            "default reaches " + std::to_string(coarsest) + " and a bare chain reaches " +
                std::to_string(stalled_ratio) + ", so neither mechanism is contributing");
    }
    CHECK_TRUE(stalled_ratio > 0.5);
}

/**
 * The sloppy retry is what moves a quilt, and it is used only when it has to be.
 *
 * With the detail drops cleared there is nothing left but simplification, so the
 * retry has to fire; with the drops in place the constrained pass is never even
 * asked on this fixture, because the drop alone meets the target. Both halves
 * being asserted is what distinguishes "the retry works" from "the retry runs on
 * everything".
 */
TEST(BuildingLod, the_sloppy_retry_fires_only_when_the_constrained_pass_stalls) {
    const Mesh building = run_rule(facade_source(), 6.0, 4.0);

    BuildingLodConfig no_drops;
    no_drops.detail_drops.clear();
    const BuildingLod retried = build_building_lod(building, no_drops);
    CHECK_TRUE(retried.sloppy_levels > 0);

    BuildingLodConfig off = no_drops;
    off.allow_sloppy = false;
    const BuildingLod constrained = build_building_lod(building, off);
    CHECK_EQ(constrained.sloppy_levels, std::size_t{0});

    // The retry is kept only when it is strictly smaller than what the
    // constrained pass produced. Asserted, not guarded: a regression that
    // shortens either chain must fail this test rather than delete the one
    // cross-configuration comparison in it.
    if (retried.levels.size() < 2u || constrained.levels.size() < 2u) {
        stratum::test::report_failure(
            __FILE__, __LINE__, "both chains have a simplified level to compare",
            "retried has " + std::to_string(retried.levels.size()) + " level(s) and constrained "
            "has " + std::to_string(constrained.levels.size()) + ", so the comparison below "
            "cannot be made");
        return;
    }
    CHECK_TRUE(triangle_count(retried.levels[1]) < triangle_count(constrained.levels[1]));

    // A welded, closed tower does not need the retry: the constrained pass
    // reaches its ratios on geometry that is not a quilt.
    //
    // The tower is also where "kept only when strictly smaller" is load-bearing
    // rather than decorative. Its third ratio asks for a tenth, the constrained
    // pass stalls at 104 triangles against a target of 64 because the ground lock
    // pins the bottom two rows, so the retry DOES run -- and comes back no
    // smaller, because the same lock binds it. Keeping that result regardless
    // would put a sloppy level in a chain that has no use for one, and
    // sloppy_levels would read 1.
    BuildingLodConfig tower_cfg;
    tower_cfg.detail_drops.clear();
    const BuildingLod tower = build_building_lod(make_tower(8, 10, 12.0f, 8.0f, 20.0f, 5.0f),
                                                 tower_cfg);
    CHECK_EQ(tower.sloppy_levels, std::size_t{0});

    // FOUR levels, exactly: one per ratio, none of them dropped. Not "at least
    // three" -- that is what a chain which kept the retry's larger result and
    // then threw the level away for failing to reduce also produces, and
    // sloppy_levels cannot say so because it is only counted once a level is
    // kept. The length of the chain is where that shows.
    CHECK_EQ(tower.levels.size(), std::size_t{4});
    CHECK_EQ(tower.switch_distances.size(), std::size_t{4});
}

/**
 * The ground lock reaches meshopt_simplifySloppy, and the sloppy level it
 * produces keeps the base, the extents and the footprint.
 *
 * Nothing else in this suite constrains a sloppy level's geometry. The default
 * configuration never takes that path -- the detail drop meets its targets first
 * -- and the tower never takes it either, so the lock was only ever tested
 * against the constrained pass, which is the pass that needs it least.
 *
 * The fixture is the facade with its drops cleared, which forces the retry, and a
 * `ground_band` of 4.5 m, which is the shopfront. That is a deliberate abuse of a
 * setting meant for a base ring, and it is the only way found to get a DENSE
 * locked set and the sloppy path at the same time: the facade's actual base ring
 * is the four corners of a rectangle, and a simplifier keeps those anyway. With
 * the band the sloppy level keeps all 65 positions below 4.5 m; with it at zero
 * the same level keeps 16 of them. The second half is what makes the first mean
 * something.
 */
TEST(BuildingLod, the_ground_lock_reaches_the_sloppy_pass) {
    const Mesh building = run_rule(facade_source(), 6.0, 4.0);
    constexpr double kBand = 4.5;

    BuildingLodConfig cfg;
    cfg.detail_drops.clear();
    cfg.ground_band = static_cast<float>(kBand);
    const BuildingLod locked = build_building_lod(building, cfg);

    if (locked.levels.size() < 2u || locked.sloppy_levels == 0u) {
        stratum::test::report_failure(
            __FILE__, __LINE__, "the fixture takes the sloppy path",
            "chain has " + std::to_string(locked.levels.size()) + " level(s) and " +
                std::to_string(locked.sloppy_levels) +
                " sloppy, so nothing here constrains a sloppy level");
        return;
    }

    const std::set<PosKey> pinned = positions_below(locked.levels[0], kBand);
    CHECK_TRUE(pinned.size() >= 60u);

    const double hull0 = plan_hull_area(locked.levels[0]);
    const stratum::BoundingBox3D& reference = locked.levels[0].bounds;
    const double tolerance = 0.02 * static_cast<double>(reference.radius());

    for (std::size_t i = 1; i < locked.levels.size(); ++i) {
        const std::set<PosKey> kept = positions_below(locked.levels[i], kBand);
        for (const PosKey& position : pinned) {
            if (kept.find(position) == kept.end()) {
                stratum::test::report_failure(
                    __FILE__, __LINE__, "a locked position survives the sloppy pass",
                    "level " + std::to_string(i) + " keeps " + std::to_string(kept.size()) +
                        " of " + std::to_string(pinned.size()) + " locked positions");
                break;
            }
        }
        CHECK_NEAR(lowest_referenced_y(locked.levels[i]),
                   lowest_referenced_y(locked.levels[0]), 1e-6);

        // The extents and the footprint of a clustered level. A sloppy pass that
        // drags the ridge down or pulls a corner in changes these first.
        const stratum::BoundingBox3D& box = locked.levels[i].bounds;
        CHECK_NEAR(static_cast<double>(box.min.x), static_cast<double>(reference.min.x), tolerance);
        CHECK_NEAR(static_cast<double>(box.min.y), static_cast<double>(reference.min.y), tolerance);
        CHECK_NEAR(static_cast<double>(box.min.z), static_cast<double>(reference.min.z), tolerance);
        CHECK_NEAR(static_cast<double>(box.max.x), static_cast<double>(reference.max.x), tolerance);
        CHECK_NEAR(static_cast<double>(box.max.y), static_cast<double>(reference.max.y), tolerance);
        CHECK_NEAR(static_cast<double>(box.max.z), static_cast<double>(reference.max.z), tolerance);
        CHECK_NEAR(plan_hull_area(locked.levels[i]), hull0, hull0 * 0.03);
    }

    // Without the band the same sloppy level does NOT keep them, so the lock is
    // what is holding them and not the clusterer's own taste.
    BuildingLodConfig loose = cfg;
    loose.ground_band = 0.0f;
    const BuildingLod unlocked = build_building_lod(building, loose);
    if (unlocked.levels.size() < 2u) {
        stratum::test::report_failure(__FILE__, __LINE__,
                                      "the unlocked chain has a level to compare",
                                      "chain has " + std::to_string(unlocked.levels.size()) +
                                          " level(s)");
        return;
    }
    const std::set<PosKey> loose_kept = positions_below(unlocked.levels.back(), kBand);
    if (!(loose_kept.size() < pinned.size())) {
        stratum::test::report_failure(
            __FILE__, __LINE__, "the ground band is what pins the sloppy level",
            "with ground_band = 0 the coarsest level still keeps " +
                std::to_string(loose_kept.size()) + " of " + std::to_string(pinned.size()) +
                " positions, so the locked run above proves nothing");
    }
}

// ============================================================================
// The windows
// ============================================================================

/**
 * Dropping the returns leaves the opening covered.
 *
 * A window is 28 triangles: 6 of reveal, 8 of frame, 2 of glazing, 12 of sill.
 * The returns -- reveal and sill -- are 18 of them and read only in raking light,
 * so they are what a coarse level sheds. What must not change is whether you can
 * see through the wall: the frame and the glazing tile the opening exactly
 * between them, and they stay.
 *
 * The measured number is the covered area of the opening, 1.2 x 2.0 = 2.4 m2,
 * before and after. It is unchanged by the drop because the reveal projects to
 * nothing through the opening -- a jamb is perpendicular to the wall -- and the
 * sill hangs below it.
 */
TEST(BuildingLod, dropping_the_returns_leaves_the_opening_covered) {
    const Mesh window = one_window();
    CHECK_TRUE(triangle_count(window) > 0);

    const double before = opening_coverage(window);
    CHECK_NEAR(before, kTileWidth * kTileHeight, 1e-6);

    const Mesh dropped = drop_detail_keys(window, first_drops());
    CHECK_NEAR(opening_coverage(dropped), kTileWidth * kTileHeight, 1e-6);

    // It really did drop something, and only what it was asked to.
    CHECK_TRUE(triangle_count(dropped) < triangle_count(window));
    CHECK_EQ(triangles_with_key(dropped, facade_material(FacadePart::Reveal)), std::size_t{0});
    CHECK_EQ(triangles_with_key(dropped, facade_material(FacadePart::Sill)), std::size_t{0});
    CHECK_EQ(triangles_with_key(dropped, facade_material(FacadePart::Glass)),
             triangles_with_key(window, facade_material(FacadePart::Glass)));
    CHECK_EQ(triangles_with_key(dropped, facade_material(FacadePart::Frame)),
             triangles_with_key(window, facade_material(FacadePart::Frame)));

    // The documented no-compaction contract: the result still addresses the input's
    // vertex array, which is what lets a lock array survive the drop.
    CHECK_EQ(dropped.vertices.size(), window.vertices.size());
    CHECK_TRUE(indices_are_sane(dropped));
}

/**
 * Dropping a covering plane is what opens a hole, and the coverage metric sees it.
 *
 * The mutation that proves the test above is not vacuous. Remove the glazing and
 * the frame instead of the reveal and the sill -- the same number of triangles,
 * near enough -- and the opening's covered area goes to zero: the wall now has a
 * hole in it that you can see the inside of the building through.
 *
 * This is also the assertion that guards the default table: a future edit that
 * adds Glass or Panel to default_facade_detail_drops() is exactly this mutation.
 */
TEST(BuildingLod, dropping_a_covering_plane_opens_a_hole) {
    const Mesh window = one_window();

    const std::vector<MaterialKey> covering = {facade_material(FacadePart::Glass),
                                               facade_material(FacadePart::Frame)};
    const Mesh holed = drop_detail_keys(window, covering);

    CHECK_TRUE(triangle_count(holed) > 0);
    CHECK_NEAR(opening_coverage(holed), 0.0, 1e-9);

    // And the default table never asks for that -- checked against
    // default_covering_plane_keys() rather than against a list written out here,
    // because the two lists disagreeing IS the defect. The table shipped with
    // DetailDrop{Frame, 1} on it while the frame was on the covering list and
    // while the comment beside it said in so many words that dropping the frame
    // "leaves a slot one frame-width wide around the glass". It did: 96 of 2400
    // rays cast at the front wall came through level 2.
    for (const DetailDrop& drop : default_facade_detail_drops()) {
        for (const MaterialKey& covering : default_covering_plane_keys()) {
            CHECK_FALSE(drop.key == covering);
        }
    }
    CHECK_TRUE(default_covering_plane_keys().size() >= 3u);
}

/**
 * NO LEVEL OF A REAL CHAIN IS SEE-THROUGH WHERE LEVEL 0 WAS SOLID.
 *
 * The test this suite did not have, and the defect it did not see. The coverage
 * metric above is correct and was only ever pointed at drop_detail_keys() on a
 * one-window fixture, so every level of the chain build_building_lod() actually
 * ships went unmeasured. Measured, the shipping chain was a colander: level 2 of
 * the default configuration had a slot around all twelve panes where the frame
 * had been dropped, and level 3 had the whole of all twelve openings open --
 * 14.4 m2 of a 6 x 10 m wall, a quarter of the front of the building, with the
 * inside visible through it.
 *
 * Asserted on EVERY level of EVERY configuration this file offers, because "the
 * drop step keeps the opening covered" was true the whole time and was not the
 * question.
 *
 * The second half is the pair that stops the first from being vacuous: with
 * covering_keys cleared the guard is off, the simplifier is free to treat an
 * opening's cover as ordinary geometry, and the chain must then produce a level
 * you CAN see through. If that ever stops being true the mechanism has stopped
 * being load-bearing, and that is worth failing over.
 */
TEST(BuildingLod, every_level_covers_the_openings_level_zero_covered) {
    const Mesh building = run_rule(facade_source(), 6.0, 4.0);

    // The fixture is the one the opening coordinates were worked out for: twelve
    // openings, all of them solid at level 0.
    const BuildingLod lod = build_building_lod(building);
    if (lod.levels.size() < 2u) {
        stratum::test::report_failure(__FILE__, __LINE__, "the facade chain has coarse levels",
                                      "chain has " + std::to_string(lod.levels.size()) +
                                          " level(s), so no level is measured here");
        return;
    }
    if (open_sample_points(lod.levels[0]) != 0) {
        stratum::test::report_failure(
            __FILE__, __LINE__, "level 0 covers all twelve openings",
            std::to_string(open_sample_points(lod.levels[0])) + " of " +
                std::to_string(kOpeningSampleTotal) +
                " sample points are open at level 0, so the coordinates are wrong and this test "
                "measures nothing");
        return;
    }

    struct Named {
        const char* what;
        BuildingLodConfig cfg;
    };
    std::vector<Named> configurations;
    configurations.push_back({"default", BuildingLodConfig{}});
    {
        BuildingLodConfig no_drops;
        no_drops.detail_drops.clear();
        configurations.push_back({"no detail drops", no_drops});
    }
    {
        BuildingLodConfig no_sloppy;
        no_sloppy.allow_sloppy = false;
        configurations.push_back({"no sloppy retry", no_sloppy});
    }
    {
        BuildingLodConfig deep;
        deep.ratios = {0.5f, 0.25f, 0.1f, 0.05f, 0.02f};
        configurations.push_back({"five ratios, down to a fiftieth", deep});
    }

    for (const Named& configuration : configurations) {
        const BuildingLod chain = build_building_lod(building, configuration.cfg);
        for (std::size_t i = 0; i < chain.levels.size(); ++i) {
            const int open = open_sample_points(chain.levels[i]);
            if (open != 0) {
                stratum::test::report_failure(
                    __FILE__, __LINE__, "no level is see-through where level 0 was solid",
                    std::string(configuration.what) + " level " + std::to_string(i) + " (" +
                        std::to_string(triangle_count(chain.levels[i])) + " triangles) leaves " +
                        std::to_string(open) + " of " + std::to_string(kOpeningSampleTotal) +
                        " sample points of the twelve openings open");
            }
        }
    }

    // The pair. With the covering planes unguarded the simplifier opens them, so
    // the runs above are testing a mechanism rather than a coincidence.
    BuildingLodConfig unguarded;
    unguarded.covering_keys.clear();
    const BuildingLod holed = build_building_lod(building, unguarded);
    int worst = 0;
    for (const Mesh& level : holed.levels) {
        worst = std::max(worst, open_sample_points(level));
    }
    if (worst == 0) {
        stratum::test::report_failure(
            __FILE__, __LINE__, "the covering guard is what keeps the openings covered",
            "with covering_keys cleared the chain still covers every opening at every one of its " +
                std::to_string(holed.levels.size()) +
                " levels, so the guarded runs above prove nothing");
    }
}

/**
 * A detail drop that names a covering plane is refused, not honoured quietly.
 *
 * The exact shape of the defect that shipped: default_facade_detail_drops()
 * carried DetailDrop{Frame, 1}, the frame is half of a window's cover, and the
 * chain emitted a level with a slot around every pane. Putting that row back is
 * the mutation, and the chain must lose the levels at and past its ratio rather
 * than emit them.
 */
TEST(BuildingLod, a_drop_that_names_a_covering_plane_costs_its_levels) {
    const Mesh building = run_rule(facade_source(), 6.0, 4.0);

    const BuildingLod sound = build_building_lod(building);
    if (sound.levels.size() < 3u) {
        stratum::test::report_failure(__FILE__, __LINE__, "the default chain has three levels",
                                      "chain has " + std::to_string(sound.levels.size()) +
                                          " level(s), so there is nothing to lose");
        return;
    }

    BuildingLodConfig reinstated;
    reinstated.detail_drops.push_back(DetailDrop{facade_material(FacadePart::Frame), 1u});
    const BuildingLod shortened = build_building_lod(building, reinstated);

    CHECK_TRUE(shortened.levels.size() < sound.levels.size());
    CHECK_EQ(shortened.levels.size(), shortened.switch_distances.size());
    for (std::size_t i = 0; i < shortened.levels.size(); ++i) {
        CHECK_EQ(open_sample_points(shortened.levels[i]), 0);
    }
}

/**
 * The glazing keeps its own material on the level it survives.
 *
 * Re-attribution after a whole-mesh simplify hands each triangle the key its
 * vertices agree on, and on a facade that rule alone is wrong: the glazing sits
 * INSIDE its frame, so all four of its corners are frame vertices too and the
 * vote gives every glazing triangle to the frame. The window then renders as
 * stone. Measured before the fix, all 24 glazing triangles of this fixture were
 * attributed to the frame on a level where the simplifier had not touched a
 * single triangle.
 *
 * So the first simplified level must still carry exactly the glazing level 0
 * carried.
 */
TEST(BuildingLod, the_glazing_keeps_its_material_where_it_survives) {
    const Mesh building = run_rule(facade_source(), 6.0, 4.0);
    const BuildingLod lod = build_building_lod(building);
    if (lod.levels.size() < 2u) {
        stratum::test::report_failure(__FILE__, __LINE__, "the chain has a simplified level",
                                      "chain has " + std::to_string(lod.levels.size()) +
                                          " level(s), so the glazing is never re-attributed here");
        return;
    }

    const MaterialKey glass = facade_material(FacadePart::Glass);
    const std::size_t at_level0 = triangles_with_key(lod.levels[0], glass);
    CHECK_TRUE(at_level0 > 0);
    CHECK_EQ(triangles_with_key(lod.levels[1], glass), at_level0);

    // The returns are gone from the same level, which is what paid for it.
    CHECK_EQ(triangles_with_key(lod.levels[1], facade_material(FacadePart::Reveal)),
             std::size_t{0});
    CHECK_EQ(triangles_with_key(lod.levels[1], facade_material(FacadePart::Sill)), std::size_t{0});
}

/// A key named in the drops is absent from the levels it names, and only those
TEST(BuildingLod, a_detail_drop_is_keyed_on_the_ratio_and_not_on_the_finished_level) {
    const Mesh building = run_rule(facade_source(), 6.0, 4.0);

    BuildingLodConfig cfg;
    cfg.ratios = {0.9f, 0.5f, 0.1f};
    cfg.detail_drops = {DetailDrop{facade_material(FacadePart::Sill), 1u}};

    const BuildingLod lod = build_building_lod(building, cfg);
    if (lod.levels.size() < 2u) {
        stratum::test::report_failure(__FILE__, __LINE__, "the chain has a simplified level",
                                      "chain has " + std::to_string(lod.levels.size()) +
                                          " level(s), so no drop is ever applied here");
        return;
    }

    const MaterialKey sill = facade_material(FacadePart::Sill);
    CHECK_TRUE(triangles_with_key(lod.levels[0], sill) > 0);

    // ratios[0] is 0.9, which is inside kMinLevelReduction of level 0 and is
    // therefore dropped -- so the first SURVIVING simplified level is the one
    // built from ratios[1], and the sill is gone from it. Had the drop been keyed
    // on the finished level index, that dropped candidate would have shifted the
    // sill onto a level nobody asked for.
    for (std::size_t i = 1; i < lod.levels.size(); ++i) {
        CHECK_EQ(triangles_with_key(lod.levels[i], sill), std::size_t{0});
    }
}

// ============================================================================
// Materials and switch distances
// ============================================================================

/// No level invents a material, and every level's ranges tile its index buffer
TEST(BuildingLod, no_level_carries_a_material_level_zero_did_not) {
    const Mesh building = run_rule(facade_source(), 6.0, 4.0);
    const BuildingLod lod = build_building_lod(building);
    if (lod.levels.size() < 2u) {
        stratum::test::report_failure(__FILE__, __LINE__, "the chain has a simplified level",
                                      "chain has " + std::to_string(lod.levels.size()) +
                                          " level(s), so no level but level 0 is checked");
        return;
    }

    const std::vector<uint32_t> level0 = keys_of(lod.levels[0]);
    for (std::size_t i = 0; i < lod.levels.size(); ++i) {
        std::string reason;
        if (!submeshes_tile_exactly(lod.levels[i], reason)) {
            stratum::test::report_failure(__FILE__, __LINE__, "level submeshes tile",
                                          "level " + std::to_string(i) + ": " + reason);
        }
        for (const uint32_t key : keys_of(lod.levels[i])) {
            CHECK_TRUE(std::find(level0.begin(), level0.end(), key) != level0.end());
        }
    }
}

/**
 * switch_distances is parallel to levels, ascending, starts at zero, and is
 * derived from the ACHIEVED ratio rather than the requested one.
 *
 * The formula is asserted rather than the numbers, so a change to
 * kBuildingLodSwitchFactor moves the test with the code and a change to which
 * ratio the distance is taken from does not.
 */
TEST(BuildingLod, switch_distances_come_from_the_achieved_ratio) {
    const Mesh tower = make_tower(8, 10, 12.0f, 8.0f, 20.0f, 5.0f);
    BuildingLodConfig cfg;
    cfg.detail_drops.clear();
    const BuildingLod lod = build_building_lod(tower, cfg);
    if (lod.levels.size() < 2u) {
        stratum::test::report_failure(__FILE__, __LINE__, "the tower chain has coarse levels",
                                      "chain has " + std::to_string(lod.levels.size()) +
                                          " level(s), so no switch distance is derived here");
        return;
    }

    CHECK_EQ(lod.switch_distances.size(), lod.levels.size());
    CHECK_NEAR(static_cast<double>(lod.switch_distances[0]), 0.0, 1e-9);

    const double radius = static_cast<double>(lod.levels[0].bounds.radius());
    const double level0 = static_cast<double>(triangle_count(lod.levels[0]));

    for (std::size_t i = 1; i < lod.levels.size(); ++i) {
        CHECK_TRUE(lod.switch_distances[i] > lod.switch_distances[i - 1u]);

        const double achieved = static_cast<double>(triangle_count(lod.levels[i])) / level0;
        const double expected =
            radius * static_cast<double>(kBuildingLodSwitchFactor) / std::sqrt(achieved);
        CHECK_NEAR(static_cast<double>(lod.switch_distances[i]), expected, expected * 1e-3);
    }

    // level_for_distance() picks what the distances say.
    CHECK_EQ(lod.level_for_distance(0.0f), std::size_t{0});
    CHECK_EQ(lod.level_for_distance(lod.switch_distances[1] - 0.1f), std::size_t{0});
    CHECK_EQ(lod.level_for_distance(lod.switch_distances[1]), std::size_t{1});
    CHECK_EQ(lod.level_for_distance(1.0e6f), lod.levels.size() - 1u);
}

/**
 * A level that cannot beat the previous one is dropped, with its distance.
 *
 * Asked for three ratios a hair apart, a correct chain keeps one level and not
 * three near-identical resident copies of the same geometry. The two arrays must
 * still be the same length afterwards.
 */
TEST(BuildingLod, a_level_that_does_not_reduce_is_dropped_with_its_distance) {
    const Mesh tower = make_tower(8, 10, 12.0f, 8.0f, 20.0f, 5.0f);

    BuildingLodConfig cfg;
    cfg.detail_drops.clear();
    cfg.ratios = {0.98f, 0.97f, 0.96f};
    const BuildingLod lod = build_building_lod(tower, cfg);

    // EXACTLY one level, not "fewer than four". "Fewer than four" is satisfied by
    // a chain of one level for any reason at all, including an implementation
    // that returns level 0 and stops, and the reduction loop below is then
    // vacuous. One is the right answer and it is the only right answer: all three
    // ratios are inside kMinLevelReduction of level 0, so all three candidates
    // are dropped along with their switch distances.
    CHECK_EQ(lod.levels.size(), std::size_t{1});
    CHECK_EQ(lod.switch_distances.size(), std::size_t{1});
    CHECK_EQ(triangle_count(lod.levels[0]), triangle_count(tower));

    // And the same tower with a ratio that CAN reduce does produce levels, so the
    // one above is the ratios being refused rather than this fixture being
    // unsimplifiable.
    BuildingLodConfig usable = cfg;
    usable.ratios = {0.5f};
    const BuildingLod reduced = build_building_lod(tower, usable);
    CHECK_EQ(reduced.levels.size(), std::size_t{2});
    const double reduction = 1.0 - static_cast<double>(triangle_count(reduced.levels[1])) /
                                       static_cast<double>(triangle_count(reduced.levels[0]));
    CHECK_TRUE(reduction >= 0.10);
}

/**
 * Ratios are measured against LEVEL 0, never against the previous level.
 *
 * The header's first stated invariant, and nothing tested it. Changing the one
 * line that computes the target from base_indices to previous_indices leaves
 * every other test in this file green, while the chain silently becomes a
 * compounding one: {0.5, 0.25, 0.1} stops meaning "half, a quarter and a tenth
 * of the input" and starts meaning "half, an eighth and an eightieth".
 *
 * Asked as a structural question rather than as a bound, because the structural
 * answer is unambiguous. Three ratios that are all 0.5 describe ONE level under
 * this file's rule -- the second and third ask for exactly what the first
 * delivered, cannot beat it by kMinLevelReduction, and are dropped. Under the
 * compounding reading the same three ratios describe a chain that halves three
 * times. Two levels against four; no tolerance to choose.
 */
TEST(BuildingLod, ratios_are_measured_against_level_zero) {
    const Mesh tower = make_tower(8, 10, 12.0f, 8.0f, 20.0f, 5.0f);

    BuildingLodConfig repeated;
    repeated.detail_drops.clear();
    repeated.ratios = {0.5f, 0.5f, 0.5f};
    const BuildingLod lod = build_building_lod(tower, repeated);

    CHECK_EQ(lod.levels.size(), std::size_t{2});
    CHECK_EQ(lod.switch_distances.size(), std::size_t{2});

    // Level 1 is a half of LEVEL 0, and the two ratios after it bought nothing.
    const double achieved = static_cast<double>(triangle_count(lod.levels[1])) /
                            static_cast<double>(triangle_count(lod.levels[0]));
    CHECK_NEAR(achieved, 0.5, 0.05);

    // The same reading on the facade, where the drop rather than the simplifier
    // decides the first level: a requested quarter must land near a quarter OF
    // LEVEL 0, and a compounding chain puts it near an eighth.
    const Mesh building = run_rule(facade_source(), 6.0, 4.0);
    const BuildingLod facade = build_building_lod(building);
    if (facade.levels.size() < 3u) {
        stratum::test::report_failure(__FILE__, __LINE__, "the facade chain reaches its third level",
                                      "chain has " + std::to_string(facade.levels.size()) +
                                          " level(s), so the second ratio is never measured");
        return;
    }
    const double quarter = static_cast<double>(triangle_count(facade.levels[2])) /
                           static_cast<double>(triangle_count(facade.levels[0]));
    if (!(std::fabs(quarter - 0.25) <= 0.2)) {
        stratum::test::report_failure(
            __FILE__, __LINE__, "a requested quarter lands near a quarter of level 0",
            std::to_string(triangle_count(facade.levels[2])) + " of " +
                std::to_string(triangle_count(facade.levels[0])) + " triangles is " +
                std::to_string(quarter) + " of level 0");
    }
}

// ============================================================================
// Determinism
// ============================================================================

/**
 * Two runs over the same input produce identical chains.
 *
 * A building's chain is built off the main thread and cached, and a level that
 * varies run to run poisons the cache. Compared field by field rather than by a
 * dump, because a dump that summarises is a dump that can miss what changed.
 */
TEST(BuildingLod, the_chain_is_deterministic) {
    const Mesh building = run_rule(facade_source(), 6.0, 4.0);

    const BuildingLod first = build_building_lod(building);
    const BuildingLod second = build_building_lod(building);

    // Not vacuous: every assertion below is an equality between two runs, and an
    // implementation that always returned an empty chain would satisfy all of
    // them. There has to be something to compare before comparing it means
    // anything.
    if (first.levels.size() < 3u) {
        stratum::test::report_failure(__FILE__, __LINE__, "there is a chain to compare",
                                      "the chain has " + std::to_string(first.levels.size()) +
                                          " level(s), so comparing two runs of it proves little");
        return;
    }
    for (const Mesh& level : first.levels) {
        CHECK_TRUE(triangle_count(level) > 0);
    }

    CHECK_EQ(first.levels.size(), second.levels.size());
    CHECK_EQ(first.switch_distances.size(), second.switch_distances.size());
    CHECK_EQ(first.sloppy_levels, second.sloppy_levels);
    if (first.levels.size() != second.levels.size()) return;

    for (std::size_t i = 0; i < first.levels.size(); ++i) {
        if (!meshes_are_identical(first.levels[i], second.levels[i])) {
            stratum::test::report_failure(__FILE__, __LINE__, "levels are identical across runs",
                                          "level " + std::to_string(i) + " differs");
        }
        CHECK_NEAR(static_cast<double>(first.switch_distances[i]),
                   static_cast<double>(second.switch_distances[i]), 1e-9);
    }
}

/**
 * The chain holds its shape: the bounding box of every level is level 0's.
 *
 * Not a silhouette proof on its own -- a box survives deleting everything but the
 * corners -- which is why it is asserted alongside the base-ring and coverage
 * tests rather than instead of them. What it does catch is the failure mode the
 * sloppy pass can have: a clusterer that drags the ridge down or pulls a corner
 * in changes these numbers first.
 */
TEST(BuildingLod, every_level_keeps_the_extents_of_level_zero) {
    const Mesh building = run_rule(facade_source(), 6.0, 4.0);

    // Both configurations, because the DEFAULT one never takes the sloppy path --
    // the detail drop meets its targets first -- and the clusterer is the thing
    // an extents test is for. Running only the default leaves the failure mode
    // named in this comment unwatched.
    BuildingLodConfig no_drops;
    no_drops.detail_drops.clear();

    const BuildingLod chains[2] = {build_building_lod(building),
                                   build_building_lod(building, no_drops)};
    CHECK_TRUE(chains[1].sloppy_levels > 0);

    for (const BuildingLod& lod : chains) {
        if (lod.levels.size() < 2u) {
            stratum::test::report_failure(__FILE__, __LINE__, "the chain has a coarse level",
                                          "chain has " + std::to_string(lod.levels.size()) +
                                              " level(s), so no extents are compared");
            continue;
        }
        const stratum::BoundingBox3D& reference = lod.levels[0].bounds;
        const double tolerance = 0.02 * static_cast<double>(reference.radius());
        const double hull = plan_hull_area(lod.levels[0]);

        for (std::size_t i = 1; i < lod.levels.size(); ++i) {
            const stratum::BoundingBox3D& box = lod.levels[i].bounds;
            CHECK_NEAR(static_cast<double>(box.min.x), static_cast<double>(reference.min.x),
                       tolerance);
            CHECK_NEAR(static_cast<double>(box.min.y), static_cast<double>(reference.min.y),
                       tolerance);
            CHECK_NEAR(static_cast<double>(box.min.z), static_cast<double>(reference.min.z),
                       tolerance);
            CHECK_NEAR(static_cast<double>(box.max.x), static_cast<double>(reference.max.x),
                       tolerance);
            CHECK_NEAR(static_cast<double>(box.max.y), static_cast<double>(reference.max.y),
                       tolerance);
            CHECK_NEAR(static_cast<double>(box.max.z), static_cast<double>(reference.max.z),
                       tolerance);

            // A box is blind to a corner cut off at 45 degrees and to a wall that
            // has holes in it. The hull catches the first; see
            // every_level_covers_the_openings_level_zero_covered for the second.
            CHECK_NEAR(plan_hull_area(lod.levels[i]), hull, hull * 0.03);
        }
    }
}
